version: '3'
services:
  prom:
    # depends_on: 
    #   - minio1
    image: prom/prometheus:latest
    volumes:
      - ./prom_conf.yml:/etc/prometheus/prometheus.yml
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: always
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
